#!/bin/sh

usage () {
  echo "usage: service-exec <stack-name> <service-name>.<service-index> [command]"
  exit;
}

CMD="/bin/bash"

if [ -z "$1" ]; then usage; fi
if [ -z "$2" ]; then usage; fi
if [ -n "$3" ]; then CMD=$3; fi

SERVICE_LINE=`docker stack ps $1 | grep Running | grep $1_$2`
NODE=`echo $SERVICE_LINE | awk '{print $4}'`
SERVICE_ID=`echo $SERVICE_LINE | awk '{print $2"."$1}'`
CONTAINER_ID=`ssh $NODE docker container ls | grep $SERVICE_ID | awk '{print $1}'`

echo "executing '$CMD' on stack '$1', service '$2', host '$NODE'..."
ssh -t $NODE docker exec -it $CONTAINER_ID $CMD
